FROM mysql:latest

# autora del Dockerfile.
LABEL maintainer="Liliana Parada Sanchez"

ENV MYSQL_DATABASE="proyectoservlet"
ENV MYSQL_ROOT_PASSWORD="root"

COPY ./BaseDatos/proyectoservlet.sql /docker-entrypoint-initdb.d/proyectoservlet.sql